# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('password', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='AllowedPeerIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('ip_range', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'allowed_peer_ip',
            },
        ),
        migrations.CreateModel(
            name='DeniedPeerIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('ip_range', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'denied_peer_ip',
            },
        ),
        migrations.CreateModel(
            name='OauthKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('ikm_key', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('as_rs_alg', models.CharField(blank=True, max_length=64, null=True)),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'oauth_key',
            },
        ),
        migrations.CreateModel(
            name='TurnOriginToRealm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=127, null=True, unique=True)),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'turn_origin_to_realm',
            },
        ),
        migrations.CreateModel(
            name='TurnRealmOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('opt', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'turn_realm_option',
            },
        ),
        migrations.CreateModel(
            name='TurnSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('value', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'turn_secret',
            },
        ),
        migrations.CreateModel(
            name='TurnusersLt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm', models.CharField(blank=True, max_length=127, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('hmackey', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'turnusers_lt',
            },
        ),
        migrations.AlterUniqueTogether(
            name='turnuserslt',
            unique_together=set([('realm', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='turnsecret',
            unique_together=set([('realm', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='turnrealmoption',
            unique_together=set([('realm', 'opt')]),
        ),
        migrations.AlterUniqueTogether(
            name='deniedpeerip',
            unique_together=set([('realm', 'ip_range')]),
        ),
        migrations.AlterUniqueTogether(
            name='allowedpeerip',
            unique_together=set([('realm', 'ip_range')]),
        ),
    ]
